[versions]
accompanistVersion = "0.37.3"
activityComposeVersion = "1.13.0"
androidExpandabletextview = "74f653343d"
androidGradlePlugin = "9.3.1"
animationVersion = "1.12.0"
annotation = "1.10.0"
shizuku = "13.1.5"
appcompat = "1.8.0"
autofittextview = "0.2.1"
billing = "9.1.0"
bugsnagAndroid = "6.26.1"
bugsnagAndroidGradle = "8.2.0"
collapsiblepreferencecategory = "75d1f8b5c5"
colorpicker = "c300c66e93"
composeintroslider = "d273cf5734"
constraintlayout = "2.2.2"
core = "5.2.2"
coreKtx = "1.19.0"
coreVersion = "4.6.2"
foundationVersion = "1.12.0"
gson = "2.14.0"
hiddenapibypass = "6.1"
indicatorfastscroll = "1.4.0"
kotlin = "2.4.10"
kotlinxCoroutines = "1.11.0"
lifecycleRuntimeKtxVersion = "2.11.0"
material = "1.14.0"
material3Version = "1.4.0"
materialVersion = "7b22984aee"
navigationFragmentKtx = "2.9.8"
patreonsupportersretrieval = "8436bbdbdc"
preferenceKtx = "1.2.1"
recyclerview = "1.4.0"
recyclerviewAnimators = "4.0.2"
relinker = "1.4.5"
runtimeVersion = "1.12.0"
seekbarpreference = "1b37341e49"
slidingpanelayout = "1.2.0"
systemuitunersystemsettings = "8d359714d9"
taskerpluginlibrary = "0.4.10"
uiToolingPreviewVersion = "1.12.0"
workRuntimeKtx = "2.11.2"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanistVersion" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
android-expandableTextView = { module = "com.github.zacharee:Android-ExpandableTextView", version.ref = "androidExpandabletextview" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "animationVersion" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
autofittextview = { module = "me.grantland:autofittextview", version.ref = "autofittextview" }
billing = { module = "com.android.billingclient:billing", version.ref = "billing" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billing" }
bugsnag-android = { module = "com.bugsnag:bugsnag-android", version.ref = "bugsnagAndroid" }
collapsiblePreferenceCategory = { module = "com.github.zacharee:CollapsiblePreferenceCategory", version.ref = "collapsiblepreferencecategory" }
colorpicker = { module = "com.github.zacharee:colorpicker", version.ref = "colorpicker" }
composeIntroSlider = { module = "com.github.zacharee:ComposeIntroSlider", version.ref = "composeintroslider" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
libsu-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundationVersion" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "foundationVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
markwon-html = { module = "io.noties.markwon:html", version.ref = "coreVersion" }
indicatorFastScroll = { module = "com.github.reddit:IndicatorFastScroll", version.ref = "indicatorfastscroll" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
markwon-core = { module = "io.noties.markwon:core", version.ref = "coreVersion" }
material = { module = "com.google.android.material:material", version.ref = "material" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3Version" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
patreonSupportersRetrieval = { module = "com.github.zacharee:PatreonSupportersRetrieval", version.ref = "patreonsupportersretrieval" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
recyclerview-animators = { module = "jp.wasabeef:recyclerview-animators", version.ref = "recyclerviewAnimators" }
relinker = { module = "com.getkeepsafe.relinker:relinker", version.ref = "relinker" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtimeVersion" }
seekBarPreference = { module = "com.github.zacharee:SeekBarPreference", version.ref = "seekbarpreference" }
slidingpanelayout = { module = "androidx.slidingpanelayout:slidingpanelayout", version.ref = "slidingpanelayout" }
systemUITunerSystemSettings = { module = "com.github.zacharee:SystemUITunerSystemSettings", version.ref = "systemuitunersystemsettings" }
taskerpluginlibrary = { module = "com.joaomgcd:taskerpluginlibrary", version.ref = "taskerpluginlibrary" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "uiToolingPreviewVersion" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreviewVersion" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
zacharee-material = { module = "com.github.zacharee:material", version.ref = "materialVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
bugsnag-android = { id = "com.bugsnag.android.gradle", version.ref = "bugsnagAndroidGradle" }
